[env:adafruit_feather_esp32s3]
board = adafruit_feather_esp32s3

platform = espressif32 @ ^6.0.1

#platform_packages =
#    platformio/framework-arduinoespressif32 @ https://github.com/espressif32/arduino-esp32.git
#    platformio/tool-esptoolpy@1.40300.0

board_build.arduino.upstream_packages = no
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags = -std=gnu++17

lib_deps =
    bblanchon/ArduinoJson @ ^7
